create table filme (id int8 not null, diretor varchar(255), genero varchar(255), nome varchar(255), quantidade int8, primary key (id));
create table historico (id int8 not null, primary key (id));
create table locacao (id int8 not null, data_devolucao timestamp, data_locacao timestamp, data_para_devolucao timestamp, devolvido boolean, usuario_id int8, primary key (id));
create table locacao_filmes (locacao_id int8 not null, filme_id int8 not null);
create table usuario (id int8 not null, cpf varchar(255), data_nascimento date, nome varchar(255), sexo varchar(255), primary key (id));
create sequence filme_id_seq start 1 increment 1;
create sequence historico_id_seq start 1 increment 1;
create sequence locacao_id_seq start 1 increment 1;
create sequence usuario_id_seq start 1 increment 1;
alter table if exists locacao add constraint FKkktfq622phc5otk6901ju9eqk foreign key (usuario_id) references usuario;
alter table if exists locacao_filmes add constraint FKqbvl80vidyo2yqjfo7eq4q160 foreign key (filme_id) references filme;
alter table if exists locacao_filmes add constraint FKesamx4mmtfo78k5l6y74xjx3h foreign key (locacao_id) references locacao;
